/*

id: 课程 id，
courses_name： 课程名称
auth：作者
price：价格
image:课程图片
time：时长
date:上线时间
desc：课程描述说明
tag：课程标签
play_count:播放次数
other：备注
boutique：是否是精品
 category:课程分类,
 */

let Courses = [
    {
        id:0,
        courses_name:'Cordova开发环境配置',
        auth:'Davie',
        price:'免费',
        image:'http://ogu06un9p.bkt.clouddn.com/cordova.jpg',
        time:'',
        desc:'',
        tag:'',
        date:'',
        play_count:0,
        othe:'',
        boutique:false,
        category:'Mobile',
        chapters:[
             {
                id:0,
                serial_number:'1-1',
                name:'Cordova开发环境配置-01',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/cordova01.mp4'
            },
             {
                id:1,
                serial_number:'1-2',
                name:'Cordova开发环境配置-02',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/cordova02.mp4'
            }
        ]

    },
    {
        id:1,
        courses_name:'ECMAScript6精讲',
        auth:'Davie',
        price:'免费',
        image:'http://ogu06un9p.bkt.clouddn.com/js.png',
        time:'',
        desc:'',
        tag:'',
        date:'',
        play_count:0,
        othe:'',
        boutique:true,
        category:'JavaScript',
        chapters:[
             {
                id:0,
                serial_number:'1-1',
                name:'使用let定义变量',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-01-let.mp4'
            },
             {
                id:1,
                serial_number:'1-2',
                name:'使用cost定义变量',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-02-const.mp4'
            },
            {
                id:2,
                serial_number:'1-3',
                name:'全局变量和window的属性',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-03-%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F.mp4'
            },
            {
                id:3,
                serial_number:'1-3',
                name:'数组的解构和赋值-01',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-04-array.mp4'
            },
            {
                id:4,
                serial_number:'1-4',
                name:'数组的解构和赋值-02',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-05-array2.mp4'
            },
            {
                id:5,
                serial_number:'1-5',
                name:'对象的结构和赋值',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-06-obj.mp4'
            },
            {
                id:6,
                serial_number:'1-6',
                name:'箭头函数',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-07-function.mp4'
            },
            {
                id:7,
                serial_number:'1-7',
                name:'函数的参数',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-08-arg.mp4'
            },
            {
                id:8,
                serial_number:'1-8',
                name:'字符串新增方法',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-09-string.mp4'
            },
            {
                id:9,
                serial_number:'1-9',
                name:'面相对象编程思想',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-10-%E9%9D%A2%E8%AF%95%E5%AF%B9%E8%B1%A1.mp4'
            },
             {
                id:10,
                serial_number:'1-10',
                name:'使用class定义类',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-11-class.mp4'
            },
             {
                id:11,
                serial_number:'1-12',
                name:'模块化',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/es6-12-module.mp4'
            },
        ]

    },
     {
        id:2,
        courses_name:'AngularJs入门',
        auth:'Davie',
        price:'免费',
        image:'http://ogu06un9p.bkt.clouddn.com/ng.png',
        time:'',
        desc:'',
        tag:'',
        date:'',
        play_count:0,
        othe:'',
        boutique:true,
        category:'Angular',
        chapters:[
             {
                id:0,
                serial_number:'1-1',
                name:'Angularjs简介',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular_01.mp4'
            },
             {
                id:1,
                serial_number:'1-2',
                name:'Angularjs 指令',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular-02.mp4'
            },
            {
                id:1,
                serial_number:'1-3',
                name:'控制器',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular-03.mp4'
            },
            {
                id:1,
                serial_number:'1-4',
                name:'作用域',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular-04.mp4'
            },
            {
                id:1,
                serial_number:'1-5',
                name:'$watch && $apply',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular-05.mp4'
            },
            {
                id:1,
                serial_number:'1-6',
                name:'内置服务',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular-06-%E5%86%85%E7%BD%AE%E6%9C%8D%E5%8A%A1.mp4'
            },
            {
                id:1,
                serial_number:'1-7',
                name:'过滤器',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular-07-%E8%BF%87%E6%BB%A4%E5%99%A82.mp4'
            },
             {
                id:1,
                serial_number:'1-8',
                name:'依赖注入',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular-08-%E4%BE%9D%E8%B5%96%E6%B3%A8%E5%85%A51.mp4'
            },
             {
                id:1,
                serial_number:'1-9',
                name:'自定义服务',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular-09-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9C%8D%E5%8A%A12.mp4'
            },
             {
                id:1,
                serial_number:'1-10',
                name:'数据交互',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular-10-http.mp4'
            },
             {
                id:1,
                serial_number:'1-11',
                name:'条件判断',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular-11-ng-if.mp4'
            },
             {
                id:1,
                serial_number:'1-11',
                name:'路由',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/angular-12-route.mp4'
            }
        ]

    },
     {
        id:3,
        courses_name:'ReactJs基础',
        auth:'Davie',
        price:'免费',
        image:'http://ogu06un9p.bkt.clouddn.com/react.png',
        time:'',
        desc:'',
        tag:'',
        date:'',
        play_count:0,
        othe:'',
        boutique:true,
        category:'React',
        chapters:[
             {
                id:0,
                serial_number:'1-1',
                name:'react',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/react-01.mp4'
            },
             {
                id:0,
                serial_number:'1-2',
                name:'react',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/react-02.mp4'
            },
             {
                id:0,
                serial_number:'1-3',
                name:'react',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/react-03.mp4'
            },
             {
                id:0,
                serial_number:'1-4',
                name:'react',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/react-04.mp4'
            },
             {
                id:0,
                serial_number:'1-5',
                name:'react',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/react-05.mp4'
            },
             {
                id:0,
                serial_number:'1-6',
                name:'react',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/react-06.mp4'
            },
             {
                id:0,
                serial_number:'1-7',
                name:'react',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/react-07.mp4'
            },
             {
                id:0,
                serial_number:'1-8',
                name:'react',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/react-08.mp4'
            },
            {
                id:0,
                serial_number:'1-9',
                name:'react',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/react-09.mp4'
            }
            

        ]

    },

    {
        id:4,
        courses_name:'项目答辩',
        auth:'Davie',
        price:'免费',
        image:'http://ogu06un9p.bkt.clouddn.com/xhslogo.png',
        time:'',
        desc:'',
        tag:'',
        date:'',
        play_count:0,
        othe:'',
        boutique:true,
        category:'项目答辩',
        chapters:[
             {
                id:0,
                serial_number:'1-1',
                name:'小红书项目答辩--徐莹莹',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/job_xhs-%E5%B0%8F%E7%BA%A2%E4%B9%A6%E7%AD%94%E8%BE%A9--%E5%BE%90%E8%8E%B9%E8%8E%B9.MP4'
            },
             {
                id:1,
                serial_number:'1-1',
                name:'小红书项目答辩--陈欣欣',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/job_xhs-%E5%B0%8F%E7%BA%A2%E4%B9%A6%E7%AD%94%E8%BE%A9-%E9%99%88%E6%AC%A3%E6%AC%A3.mp4'
            },
            {
                id:2,
                serial_number:'1-1',
                name:'小红书项目答辩--马思',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/job_xhs-%E5%B0%8F%E7%BA%A2%E4%B9%A6%E8%AE%B2%E8%A7%A3--%E9%A9%AC%E6%80%9D.mp4'
            },
            {
                id:3,
                serial_number:'1-1',
                name:'小红书项目答辩--章凯旋',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/xhs-%E5%B0%8F%E7%BA%A2%E4%B9%A6%E9%A1%B9%E7%9B%AE%E7%AD%94%E8%BE%A9--%E7%AB%A0%E5%87%AF%E6%97%8B.mp4'
            },
            {
                id:4,
                serial_number:'1-1',
                name:'小红书项目答辩--田粤浩',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/xhs-%E7%94%B0%E7%B2%A4%E6%B5%A9%E5%B0%8F%E7%BA%A2%E4%B9%A6.mp4'
            },
            {
                id:5,
                serial_number:'1-1',
                name:'小红书项目答辩--连松峰',
                time:'',
                url:'http://onm7p8xac.bkt.clouddn.com/xhs-%E8%BF%9E%E6%9D%BE%E5%B3%B0%E8%AE%B2%E8%A7%A3%E5%B0%8F%E7%BA%A2%E4%B9%A6LP_20170406095507.mp4'
            }
           

        ]

    },
    
]

module.exports = Courses;